# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x0eproductService\"@\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\"M\n\x0cOrderMessage\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12(\n\x05items\x18\x02 \x03(\x0b\x32\x19.productService.OrderItem\"=\n\x11OrderConfirmation\x12\x17\n\x0f\x63onfirmation_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"V\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\"8\n\x0bProductList\x12)\n\x08products\x18\x01 \x03(\x0b\x32\x17.productService.Product\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2^\n\x0cOrderService\x12N\n\x0bSubmitOrder\x12\x1c.productService.OrderMessage\x1a!.productService.OrderConfirmation2\x9e\x01\n\x0eProductService\x12\x41\n\x0bGetProducts\x12\x15.productService.Empty\x1a\x1b.productService.ProductList\x12I\n\x0eGetProductById\x12\x1e.productService.ProductRequest\x1a\x17.productService.ProductB$\n\x13productService.gRPCB\x0b\x61lternativeP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023productService.gRPCB\013alternativeP\001'
  _globals['_ORDERITEM']._serialized_start=31
  _globals['_ORDERITEM']._serialized_end=95
  _globals['_ORDERMESSAGE']._serialized_start=97
  _globals['_ORDERMESSAGE']._serialized_end=174
  _globals['_ORDERCONFIRMATION']._serialized_start=176
  _globals['_ORDERCONFIRMATION']._serialized_end=237
  _globals['_PRODUCT']._serialized_start=239
  _globals['_PRODUCT']._serialized_end=325
  _globals['_PRODUCTLIST']._serialized_start=327
  _globals['_PRODUCTLIST']._serialized_end=383
  _globals['_PRODUCTREQUEST']._serialized_start=385
  _globals['_PRODUCTREQUEST']._serialized_end=413
  _globals['_EMPTY']._serialized_start=415
  _globals['_EMPTY']._serialized_end=422
  _globals['_ORDERSERVICE']._serialized_start=424
  _globals['_ORDERSERVICE']._serialized_end=518
  _globals['_PRODUCTSERVICE']._serialized_start=521
  _globals['_PRODUCTSERVICE']._serialized_end=679
# @@protoc_insertion_point(module_scope)
