apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: set-cookie-front
  namespace: storeapptest
spec:
  headers:
    customResponseHeaders:
      Set-Cookie: "store-session=front; Max-Age=300; Path=/; HttpOnly"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: set-cookie-grpc
  namespace: storeapptest
spec:
  headers:
    customResponseHeaders:
      Set-Cookie: "store-session=grpc; Max-Age=300; Path=/; HttpOnly"
