apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: store-traffic-split
  namespace: storeapptest
spec:
  weighted:
    services:
    - name: store-front
      weight: 80
    - name: store-grpc
      weight: 20

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: store-route
  namespace: storeapptest
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: store-front
      port: 80
      weight: 80
    - name: store-grpc
      port: 80
      weight: 20