apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-ingress
  namespace: storeapptest
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /                    # Define o destino da reescrita de URL
    nginx.ingress.kubernetes.io/weighted-services: '{"store-front": 80, "store-grpc": 20}'  # Balanceamento de carga 80/20
spec:
  rules:
  - host: www.storefrontsdproject.com                                      # Domínio que será acessado
    http:
      paths:
      - path: /                                                          # Caminho raiz
        pathType: Prefix
        backend:
          service:
            name: store-front                                            # Serviço que recebe 80% do tráfego
            port:
              number: 80                                                 # Porta do serviço front-end
      - path: /                                                          # Caminho raiz também
        pathType: Prefix
        backend:
          service:
            name: store-grpc                                            # Serviço que recebe 20% do tráfego
            port:
              number: 80                                                 # Porta do serviço gRPC
