apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: combined-route
  namespace: storeapptest
spec:
  entryPoints:
    - web
  routes:
    # Rota para store-front-service com cookie 'store-session=front'
    - match: HeadersRegexp(`Cookie`, `store-session=front`)
      kind: Rule
      priority: 10
      services:
        - name: store-front-service
          port: 80
    # Rota para store-grpc-service com cookie 'store-session=grpc'
    - match: HeadersRegexp(`Cookie`, `store-session=grpc`)
      kind: Rule
      priority: 10
      services:
        - name: store-grpc-service
          port: 80

    # Rota genérica para balanceamento de carga com ambos os serviços
    - match: PathPrefix(`/`)
      kind: Rule
      priority: 5
      services:
        # Balanceamento de carga com pesos
        - name: store-front-service
          port: 80
          weight: 50
        - name: store-grpc-service
          port: 80
          weight: 50
      middlewares:
        # Aplicando middleware para set-cookie específico para cada serviço
        - name: set-cookie-front  # Middleware para o store-front-service
        - name: set-cookie-grpc   # Middleware para o store-grpc-service
