apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: store-route
  namespace: storeapptest
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/store-front/`)
    kind: Rule
    services:
    - name: store-grpc
      port: 80
      weight: 20
    - name: store-front
      port: 80
      weight: 80