apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-ingress
  namespace: storeapptest
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Especifica que o Nginx deve ser usado como controlador de ingress
    nginx.ingress.kubernetes.io/load-balance: "ewma"  # Estratégia de balanceamento de carga: "ewma" (Exponential Weighted Moving Average)
    nginx.ingress.kubernetes.io/upstreams: |
      {
        "store-front": {
          "weight": 80
        },
        "store-grpc": {
          "weight": 20
        }
      }
spec:
  rules:
  - host: "storefrontsdproject.com"  # O hostname que será acessado
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: store-front
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: store-grpc
            port:
              number: 80
