apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: combined-route
  namespace: storeapptest
  annotations:
    # Habilitando sticky session com o cookie store-session
    traefik.ingress.kubernetes.io/affinity: "cookie"
    traefik.ingress.kubernetes.io/session-cookie-name: "store-session"
    traefik.ingress.kubernetes.io/session-cookie-http-only: "true"
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)  # Esse match cobre qualquer requisição para /
      kind: Rule
      priority: 10
      services:
        # Balanceamento de carga entre os dois serviços com pesos
        - name: store-front-service
          port: 80
          weight: 50
        - name: store-grpc-service
          port: 80
          weight: 50
