apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: combined-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)  # Esse match cobre qualquer requisição para /
      kind: Rule
      priority: 10
      services:
        # Balanceamento de carga entre os dois serviços com pesos
        - name: store-front-service
          port: 80
          weight: 50
        - name: store-grpc-service
          port: 80
          weight: 50
