name: Product-Service-Upload

on:
  push:
    branches:
      - dev-2  # Branch que será monitorada
    paths:
      - 'src/product-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do código-fonte
    - name: Checkout the code
      uses: actions/checkout@v2

    # Passo 2: Configurar o Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Passo 3: Login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário no Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Senha ou token de acesso no Docker Hub

    # Passo 4: Gerar a versão da imagem usando o número do build
    - name: Define image version
      id: version
      run: echo "IMAGE_VERSION=${{ github.sha }}" >> $GITHUB_ENV

    # Passo 5: Build e tag da imagem Docker
    - name: Build the Docker image
      run: |
        docker build -f ./src/product-service/Dockerfile -t grupo2sd2024/product-service:latest ./src/product-service
    
    # Passo 6: Push da imagem Docker para o Docker Hub
    - name: Push the Docker image
      run: |
        docker push grupo2sd2024/product-service:latest