name: Testing_Upload_Docker

on:
  push:
    branches:
      - dev-2  # Branch que será monitorada
    paths:
      - 'src/makeline-service/**'
      - 'src/product-service/**'
      - 'src/store-front/**'
      - 'src/store-admin/**'
      - 'src/virtual-customer/**'
      - 'src/virtual-worker/**'
      - 'src/order-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do código-fonte
    - name: Checkout the code
      uses: actions/checkout@v2

    # Passo 2: Configurar o Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Passo 3: Login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário no Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Senha ou token de acesso no Docker Hub

    # Passo 4: Gerar a versão da imagem usando o número do build
    - name: Define image version
      id: version
      run: echo "IMAGE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV

    # Passo 5: Build e tag da imagem Docker somente se a pasta foi alterada
    - name: Build and Push Docker Images
      run: |
        if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^src/makeline-service/'; then
          docker build -f ./src/makeline-service/Dockerfile -t grupo2sd2024/makeline-service:${{ env.IMAGE_VERSION }} ./src/makeline-service
          docker push grupo2sd2024/makeline-service:${{ env.IMAGE_VERSION }}
        fi

        if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^src/product-service/'; then
          docker build -f ./src/product-service/Dockerfile -t grupo2sd2024/product-service:${{ env.IMAGE_VERSION }} ./src/product-service
          docker push grupo2sd2024/product-service:${{ env.IMAGE_VERSION }}
        fi

        if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^src/store-front/'; then
          docker build -f ./src/store-front/Dockerfile -t grupo2sd2024/store-front:${{ env.IMAGE_VERSION }} ./src/store-front
          docker push grupo2sd2024/store-front:${{ env.IMAGE_VERSION }}
        fi

        if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^src/store-admin/'; then
          docker build -f ./src/store-admin/Dockerfile -t grupo2sd2024/store-admin:${{ env.IMAGE_VERSION }} ./src/store-admin
          docker push grupo2sd2024/store-admin:${{ env.IMAGE_VERSION }}
        fi

        if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^src/virtual-customer/'; then
          docker build -f ./src/virtual-customer/Dockerfile -t grupo2sd2024/virtual-customer:${{ env.IMAGE_VERSION }} ./src/virtual-customer
          docker push grupo2sd2024/virtual-customer:${{ env.IMAGE_VERSION }}
        fi

        if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^src/virtual-worker/'; then
          docker build -f ./src/virtual-worker/Dockerfile -t grupo2sd2024/virtual-worker:${{ env.IMAGE_VERSION }} ./src/virtual-worker
          docker push grupo2sd2024/virtual-worker:${{ env.IMAGE_VERSION }}
        fi

        if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^src/order-service/'; then
          docker build -f ./src/order-service/Dockerfile -t grupo2sd2024/order-service:${{ env.IMAGE_VERSION }} ./src/order-service
          docker push grupo2sd2024/order-service:${{ env.IMAGE_VERSION }}
        fi