name: Build, Push Docker and Update YAMLs

on:
  push:
    branches:
      - dev  # Mude para o branch que você preferir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do código-fonte
    - name: Checkout the code
      uses: actions/checkout@v2

    # Passo 2: Configurar o Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Passo 3: Login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      env:
        username: ${{secrets.DOCKER_USERNAME}}  # Defina seu nome de usuário no Docker Hub nas Secrets
        password: ${{secrets.DOCKER_PASSWORD}}  # Defina sua senha ou token de acesso nas Secrets

    # Passo 4: Gerar a versão da imagem usando o número do build
    - name: Define image version
      id: version
      run: echo "IMAGE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV

    # Passo 5: Build e tag da imagem Docker
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/meu-repositorio:${{ env.IMAGE_VERSION }} .

    # Passo 6: Push da imagem Docker para o Docker Hub
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/meu-repositorio:${{ env.IMAGE_VERSION }}

    # Passo 7: Atualizar arquivos YAML com a nova versão da imagem
    - name: Update Docker image version in YAMLs
      run: |
        find . -name "*.yaml" -exec sed -i "s|image: .*/meu-repositorio:.*|image: ${{ secrets.DOCKER_USERNAME }}/meu-repositorio:${{ env.IMAGE_VERSION }}|g" {} \;

    # Passo 8: Comitar as mudanças nos arquivos YAML de volta ao repositório
    - name: Commit updated YAMLs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Docker image version to ${{ env.IMAGE_VERSION }}"
        git push
