name: Build, Push Docker and Update YAMLs

on:
  push:
    branches:
      - main-never-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Define image version
      id: version
      run: echo "IMAGE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        ls -la
        docker build -f ./src/makeline-service/Dockerfile -t grupo2sd2024/makeline-service:${{ env.IMAGE_VERSION }} ./src/makeline-service
        docker build -f ./src/product-service/Dockerfile -t grupo2sd2024/product-service:${{ env.IMAGE_VERSION }} ./src/product-service
        docker build -f ./src/store-front/Dockerfile -t grupo2sd2024/store-front:${{ env.IMAGE_VERSION }} ./src/store-front
        docker build -f ./src/store-admin/Dockerfile -t grupo2sd2024/store-admin:${{ env.IMAGE_VERSION }} ./src/store-admin
        docker build -f ./src/virtual-customer/Dockerfile -t grupo2sd2024/virtual-customer:${{ env.IMAGE_VERSION }} ./src/virtual-customer
        docker build -f ./src/virtual-worker/Dockerfile -t grupo2sd2024/virtual-worker:${{ env.IMAGE_VERSION }} ./src/virtual-worker
        docker build -f ./src/order-service/Dockerfile -t grupo2sd2024/order-service:${{ env.IMAGE_VERSION }} ./src/order-service

    - name: Push the Docker image
      run: |
        docker push grupo2sd2024/makeline-service:${{ env.IMAGE_VERSION }}
        docker push grupo2sd2024/product-service:${{ env.IMAGE_VERSION }}
        docker push grupo2sd2024/store-front:${{ env.IMAGE_VERSION }}
        docker push grupo2sd2024/store-admin:${{ env.IMAGE_VERSION }}
        docker push grupo2sd2024/virtual-customer:${{ env.IMAGE_VERSION }}
        docker push grupo2sd2024/virtual-worker:${{ env.IMAGE_VERSION }}
        docker push grupo2sd2024/order-service:${{ env.IMAGE_VERSION }}

    - name: Update Docker image version in YAMLs
      run: |
        find . -name "*.yaml" -exec sed -i "s|image: .*grupo2sd2024/order-service:.*|image: grupo2sd2024/order-service:${{ env.IMAGE_VERSION }}|g" {} \;
        find . -name "*.yaml" -exec sed -i "s|image: .*grupo2sd2024/makeline-service:.*|image: grupo2sd2024/makeline-service:${{ env.IMAGE_VERSION }}|g" {} \;
        find . -name "*.yaml" -exec sed -i "s|image: .*grupo2sd2024/virtual-worker:.*|image: grupo2sd2024/virtual-worker:${{ env.IMAGE_VERSION }}|g" {} \;
        find . -name "*.yaml" -exec sed -i "s|image: .*grupo2sd2024/product-service:.*|image: grupo2sd2024/product-service:${{ env.IMAGE_VERSION }}|g" {} \;
        find . -name "*.yaml" -exec sed -i "s|image: .*grupo2sd2024/store-front:.*|image: grupo2sd2024/store-front:${{ env.IMAGE_VERSION }}|g" {} \;
        find . -name "*.yaml" -exec sed -i "s|image: .*grupo2sd2024/store-admin:.*|image: grupo2sd2024/store-admin:${{ env.IMAGE_VERSION }}|g" {} \;
        find . -name "*.yaml" -exec sed -i "s|image: .*grupo2sd2024/virtual-customer:.*|image: grupo2sd2024/virtual-customer:${{ env.IMAGE_VERSION }}|g" {} \;

    - name: Commit updated YAMLs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Docker image version to ${{ env.IMAGE_VERSION }}"
        git push
